/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
package org.opensearch.neuralsearch.transport;

import org.opensearch.action.support.nodes.BaseNodeResponse;
import org.opensearch.cluster.node.DiscoveryNode;
import org.opensearch.core.common.io.stream.StreamInput;
import org.opensearch.core.common.io.stream.StreamOutput;

import java.io.IOException;

/**
 * ClearNeuralStatsNodeResponse represents the responses generated by an individual node
 */
public class ClearNeuralStatsNodeResponse extends BaseNodeResponse {
    /**
     * Constructor
     *
     * @param in  stream
     * @throws IOException in case of I/O errors
     */
    public ClearNeuralStatsNodeResponse(StreamInput in) throws IOException {
        super(in);
    }

    /**
     * Constructor
     *
     * @param node node
     */
    public ClearNeuralStatsNodeResponse(DiscoveryNode node) {
        super(node);
    }

    @Override
    public void writeTo(StreamOutput out) throws IOException {
        super.writeTo(out);
    }
}
